resources:
- name: input-1
  type: git
  source:
    uri: https://github.com/z4ce/cf-migrate-mysql.git
jobs:
- name: some-job
  plan:
  - task: output-producer
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: bash
        args:
        - -c
        - |
          cat output
