resources:
- name: input-1
  type: git
  source:
    uri: https://github.com/z4ce/break-concourse-ui.git
jobs:
- name: some-job
  plan:
  - get: input-1
  - task: output-producer
    config:
      inputs:
      - name: input-1
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: bash
        args:
        - -c
        - |
          while read p; do
            echo $p > /dev/tty
            sleep .18
          done < input-1/output 
